import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from 'react'

import { getLocalStream } from "../scripts/microphone";

const cohere = require("cohere-ai");
cohere.init(`${process.env.COHERE_API_KEY}`);

// generate example
(async () => {
  const response = await cohere.generate({
    prompt: "Once upon a time in a magical land called",
  });
  //console.log(`Prediction: ${response.body.generations[0].text}`);
  // console.log(response.body.generations?.[0].text);
})();

// generate sentence example
(async () => {
  const response = await cohere.generate({
    prompt: "Write me a sentence relating to the words yesterday, party, great",
    model: "command-xlarge-20221108"
  });
  console.log(response.body.generations?.[0].text);
})();

// genereate sentence response example
(async () => {
  const response = await cohere.generate({
    prompt: "Respond to the sentence 'How was the party yesterday?' relating to the word 'bad'",
    model: "command-xlarge-20221108",
    num_generations: 5,
  });
  console.log(response.body.generations);
})();

export default function Home() {
  useEffect(() => {
    getLocalStream();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
